name: Build and Push Docker Images
on:
 workflow_dispatch:        
# push:                                            
#   branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name acreadeployca
    - name: Set Up Trivy
      run: |
        sudo apt update
        sudo snap install trivy
    - name: Build, Scan and Push Image 1
      run: |
        docker build -f ./FrontEnd/Dockerfile -t acreadeployca.azurecr.io/frontend:latest .
        trivy image acreadeployca.azurecr.io/frontend:latest
        docker push acreadeployca.azurecr.io/frontend:latest
    - name: Build, Scan and Push Image 2
      run: |
        docker build -f ./Backend/Dockerfile -t acreadeployca.azurecr.io/backend:latest .
        trivy image acreadeployca.azurecr.io/backend:latest
        docker push acreadeployca.azurecr.io/backend:latest
