name: Build and Push Docker Images
on:
 workflow_dispatch:        
# push:                                            
#   branches: [ master ]
jobs:

  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ACREADeployCA.azurecr.io/frontend:${{ github.sha }} --registry ACREADeployCA --file ./FrontEnd/Dockerfile
