name: Build and Push Docker Images
on:
 workflow_dispatch:        
# push:                                            
#   branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name acreadeployca
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore and build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
    - name: Depcheck to scan dependencies
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with: 
        project: 'Backend'
        path: '.'
        format: 'HTML'
        args: >
          --failOnCVSS 8  
        # fail if CVSS score is High >=8
    - name: Upload Depcheck results for Backend
      uses: actions/upload-artifact@v4
      with:
        name: Depcheck Backend report
        path: ${{github.workspace}}/reports
    - name: Build and Push frontend
      run: |
        docker build -f ./FrontEnd/Dockerfile -t acreadeployca.azurecr.io/frontend:latest .
        docker push acreadeployca.azurecr.io/frontend:latest
    - name: Run Trivy Scan on ACR Image
      uses: aquasecurity/trivy-action@0.28.0
      with: 
        image-ref: 'acreadeployca.azurecr.io/frontend:latest'
        format: 'table'
        ignore-unfixed: true
    - name: Build and Push backend
      run: |
        docker build -f ./Backend/Dockerfile -t acreadeployca.azurecr.io/backend:latest .
        docker push acreadeployca.azurecr.io/backend:latest
    - name: Run Trivy Scan on ACR Image
      uses: aquasecurity/trivy-action@0.28.0
      with: 
        image-ref: 'acreadeployca.azurecr.io/backend:latest'
        format: 'table'
        ignore-unfixed: true
        
