name: Deploy into cluster                                       
on:
 workflow_dispatch:        
# push:                                            
#   branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  

      - name: Retrive SSH Key
        run: |
          az aks get-credentials --resource-group EADeployCA2 --name carcommercecluster

      - name: Apply manifest and HPA
        run: |
          kubectl apply -f ./car-commerce.yaml
          kubectl apply -f ./hpa.yaml